### ISSUE TITLE
Is this library intended to be browser-compatible?

### ISSUE THREAD

**Issue by billyjanitsch** [es-shims/RegExp.prototype.flags#19]
The browser logos in the readme would seem to imply so, but https://github.com/es-shims/RegExp.prototype.flags/commit/c3a37276764d99c1e4f7e9467ad636fce8c92c58 introduced a transitive dependency on `has-symbols` (via `es-abstract/helpers/callBind`) which [references a property on `global`](https://github.com/inspect-js/has-symbols/blob/132fe9ce5c2e443e0570606d4568a242eb86b5f5/index.js#L3), which doesn't exist in browser environments.

@ljharb just wondering if this is expected, or an oversight.

**Comment by ljharb** [comment]
It's not an oversight at all; every bundler transforms `global` to `window` for the browser, and if they don't, then they'll be unable to correctly bundle a great many npm dependencies.

**Comment by billyjanitsch** [comment]
>every bundler transforms global to window for the browser

Webpack currently "polyfills" `global` (along with other Node-isms) by default, but this feature might be [removed in v5](https://github.com/webpack/changelog-v5/blob/7ba34483107cf092d94ddb157244d2ef460039c0/README.md#automatic-nodejs-polyfills-removed), which is around the corner. It's been encouraged to disable it manually anyway.

>if they don't, then they'll be unable to correctly bundle a great many npm dependencies

I'm not sure what you mean by "a great many", but this doesn't seem consistent with my experience. We've had Webpack's automatic polyfill feature disabled at my company for ~6 months, and across a few web apps bundling thousands of runtime npm dependencies, `regexp.prototype.flags@1.3.0` is the first one for which this has been an issue. (I'm sure it's not the first one to reference `global`, but typically I've seen modules check for `global`'s existence before accessing properties on it.) I'm sure some other modules do this too but it seems overwhelmingly uncommon, at least amongst packages which intend to be browser-compatible. Do you have other examples in mind?

Thanks for your work maintaining these shims, btw 😊 and no problem if you don't have the time or interest to continue the conversation.

**Comment by ljharb** [comment]
If webpack does decide to remove it in v5 - which I very much hope they don't - then obviously I'd have to update `has-symbols` to use https://npmjs.com/globalthis.

I reference `global` in a number of my modules, so while your experience is interesting I think it's anecdotal.
