### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by binayatdelhi** [es-shims/RegExp.prototype.flags#26]
Hi,
When I try to install regexp.prototype.flags@^1.4.1 then it fails with the message "No matching version found for regexp.prototype.flags@^1.4.1"

Later when I checked npm info regexp.prototype.flags then it shows dist-tags: latest: 1.3.1 and it doesn't shows your later version 1.4.3.

Actually one of my project dependency is using npm package "es-abstract" and in version "1.20.0" it started using "regexp.prototype.flags": "^1.4.1" (new addition in es-abstract package.json). Due to this during rpm install is failing with following error 

_npm ERR! code ETARGET
npm ERR! notarget No matching version found for regexp.prototype.flags@^1.4.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'es-abstract'
npm ERR! notarget_

Not sure if it is something which I can fix at my end or if you need to do something at your end. Please help.

Regards,
Binay K

**Comment by ljharb** [comment]
As you can see here: https://unpkg.com/browse/regexp.prototype.flags@1.4.3/ all the versions are present.

You are almost certainly using a private registry that is misconfigured (since it should be automatically pulling from the public registry).
