### ISSUE TITLE
polyfill test always fails (so uses the implementation)

### ISSUE THREAD

**Issue by jdalton** [es-shims/RegExp.prototype.flags#31]
https://github.com/es-shims/RegExp.prototype.flags/blob/195c32e7f48d09b12428442aaaa5a28a72d56287/polyfill.js#L18-L32

`calls` will always be `''`.

**Comment by ljharb** [comment]
whoops, thanks. i clearly miscopied the test from es6-shim :-) will fix.

**Comment by ljharb** [comment]
Latest node still needs to be replaced, apparently, but I'll still repair the logic.
